import { Resend } from "resend";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { resendConfigurationError } from "@/lib/email/provider";
import { canGenerateContract, canSoftDeleteLead, firstDisallowedKey, isSafeLeadSlug, LEAD_INPUT_KEYS, sellerName, SOCIAL_AUDIT_INPUT_KEYS } from "@/lib/hardening/guards";

export const runtime = "nodejs";
type Db = Awaited<ReturnType<typeof createSupabaseServerClient>>;
const tables: Record<string, string> = { proposals: "ds_proposals", emails: "ds_emails", orders: "ds_orders", checkouts: "ds_checkouts", payments: "ds_payments", contracts: "ds_contracts", handoffs: "ds_handoffs", commissions: "ds_commissions", qualifications: "ds_qualifications", diagnoses: "ds_site_diagnoses", "social-audits": "ds_social_audits", previews: "ds_previews", timeline: "ds_timeline" };
const id = (prefix: string) => `${prefix}_${crypto.randomUUID().replaceAll("-", "").slice(0, 12)}`;
const now = () => new Date().toISOString();

async function context() {
  const db = await createSupabaseServerClient();
  const { data: { user } } = await db.auth.getUser();
  if (!user) return null;
  const { data: profile } = await db.from("ds_users").select("role").eq("id", user.id).maybeSingle();
  return profile?.role === "admin" ? { db, user } : null;
}
const out = (data: unknown, status = 200) => Response.json(data, { status, headers: { "Cache-Control": "no-store" } });
const storageUnavailable = () => out({ error: "storage_unavailable" }, 503);
async function event(db: Db, lead: string | null, name: string, detail = "", demo = false) {
  await db.from("ds_timeline").insert({ id: id("evt"), lead_slug: lead, event: name, detail, is_demo: demo });
}
async function settings(db: Db) {
  const { data, error } = await db.from("ds_settings").select("key,value");
  if (error) throw error;
  return Object.fromEntries((data ?? []).map((row) => [row.key, row.value]));
}
const leadToUi = (l: Record<string, unknown>) => ({ ...l, siteAntigo: l.site_antigo, urlNova: l.url_nova, dataProposta: l.data_proposta, contratoStatus: l.contrato_status, contratoEm: l.contrato_em, docCliente: l.doc_cliente, endCliente: l.end_cliente });
const uiToLead = (l: Record<string, unknown>) => {
  const x = Object.fromEntries(Object.entries(l).filter(([key]) => LEAD_INPUT_KEYS.has(key))) as Record<string, unknown>;
  for (const [a, b] of [["siteAntigo","site_antigo"],["urlNova","url_nova"],["dataProposta","data_proposta"],["contratoStatus","contrato_status"],["contratoEm","contrato_em"],["docCliente","doc_cliente"],["endCliente","end_cliente"]]) if (a in x) { x[b] = x[a]; delete x[a]; }
  delete x.closingConfirmed;
  return x;
};

export async function GET(request: Request, { params }: { params: Promise<{ path: string[] }> }) {
  const auth = await context(); if (!auth) return out({ error: "unauthorized" }, 401);
  const { db } = auth; const parts = (await params).path; const root = parts[0];
  if (root === "settings") return out(await settings(db));
  if (root === "products") { const { data, error } = await db.from("ds_products").select("*").order("id"); return error ? storageUnavailable() : out(data); }
  if (root === "leads") { const { data, error } = await db.from("ds_leads").select("*").is("deleted_at", null).order("updated_at", { ascending: false }); return error ? storageUnavailable() : out((data ?? []).map(leadToUi)); }
  if (root === "config") return out({ contratante: await settings(db), dattavps: {} });
  if (root === "financial") {
    const [{ data: orders }, { data: payments }, { data: commissions }, { data: products }] = await Promise.all([db.from("ds_orders").select("*").eq("status", "paid"), db.from("ds_payments").select("amount,status"), db.from("ds_commissions").select("amount"), db.from("ds_products").select("id,billing")]);
    const paid = orders ?? [], received = (payments ?? []).filter((p) => p.status === "approved").reduce((a, p) => a + Number(p.amount), 0);
    const recurring = new Set((products ?? []).filter((p) => p.billing === "recurring").map((p) => p.id));
    const revenue = paid.reduce((a, o) => a + Number(o.negotiated_price), 0), cost = paid.reduce((a, o) => a + Number(o.cost), 0), margin = paid.reduce((a, o) => a + Number(o.margin), 0), mrr = paid.filter((o) => recurring.has(o.product_id)).reduce((a, o) => a + Number(o.negotiated_price), 0);
    return out({ sales: paid.length, revenue, cost, margin, received, receivable: revenue - received, mrr, projection: revenue + mrr * 12, commission: (commissions ?? []).reduce((a, c) => a + Number(c.amount), 0) });
  }
  if (root === "contracts" && parts[2] === "html") { const { data } = await db.from("ds_contracts").select("html").eq("id", parts[1]).maybeSingle(); return new Response(data?.html ?? "Contrato não encontrado", { status: data ? 200 : 404, headers: { "Content-Type": "text/html; charset=utf-8" } }); }
  if (root === "previews" && parts[1] && parts[2] !== "data") { const { data } = await db.from("ds_previews").select("content").eq("id", parts[1]).maybeSingle(); return new Response(data?.content ?? "Preview não encontrado", { status: data ? 200 : 404, headers: { "Content-Type": "text/html; charset=utf-8" } }); }
  if (tables[root]) { const fields = root === "previews" ? "id,lead_slug,kind,url,status,created_at" : "*"; const { data, error } = await db.from(tables[root]).select(fields).order("created_at", { ascending: false }); return error ? storageUnavailable() : out(data); }
  return out({ error: "route_not_found" }, 404);
}

export async function POST(request: Request, { params }: { params: Promise<{ path: string[] }> }) {
  const auth = await context(); if (!auth) return out({ error: "unauthorized" }, 401);
  const { db } = auth; const parts = (await params).path; const root = parts[0]; const body = await request.json().catch(() => ({}));
  if (root === "leads") {
    const disallowed = firstDisallowedKey(body, LEAD_INPUT_KEYS);
    if (disallowed) return out({ error: "lead_field_not_allowed" }, 400);
    if (!isSafeLeadSlug(body.slug)) return out({ error: "invalid_lead_slug" }, 400);
    if (body.status === "fechado") return out({ error: "Fechamento exige confirmação explícita e valor_fechado positivo." }, 400);
    const row = uiToLead(body); row.updated_at = now(); row.source ??= "manual"; const { error } = await db.from("ds_leads").upsert(row); return error ? storageUnavailable() : out({ ok: true });
  }
  if (root === "proposals") {
    const { data: product } = await db.from("ds_products").select("*").eq("id", body.product_id).eq("active", true).maybeSingle(); if (!product) return out({ error: "Produto não disponível" }, 400);
    const base = Number(product.base_price), price = body.negotiated_price == null || body.negotiated_price === "" ? base : Number(body.negotiated_price), discount = base - price;
    if (price <= 0 || discount > base * Number(product.max_discount_pct) / 100) return out({ error: "Preço inválido ou desconto acima do máximo" }, 400);
    const row = { id: id("prop"), lead_slug: body.lead_slug, product_id: body.product_id, base_price: base, negotiated_price: price, discount, margin: price - Number(product.cost), currency: product.currency, terms: body.terms || "Pagamento mock local", valid_until: new Date(Date.now() + Number(body.valid_days || 7) * 86400000).toISOString(), version: 1, status: "draft" };
    const { error } = await db.from("ds_proposals").insert(row); if (error) return storageUnavailable(); await event(db, row.lead_slug, "proposal.created", row.id); return out(row);
  }
  if (root === "emails" && parts[2] === "transition") return transitionEmail(db, parts[1], body.status, body.fixture);
  if (root === "emails") { const row = { id: id("email"), lead_slug: body.lead_slug, proposal_id: body.proposal_id || null, subject: String(body.subject || "Proposta DattaSeller"), body: String(body.body || "Olá, segue a proposta para sua revisão."), status: "draft", provider: "mock", attempt: 0 }; const { error } = await db.from("ds_emails").insert(row); if (error) return storageUnavailable(); await event(db, row.lead_slug, "email.draft", row.id); return out(row); }
  if (root === "orders" && parts[2] === "checkout") return checkout(db, parts[1], body.result);
  if (root === "orders" && parts[2] === "payment") return payment(db, parts[1], body.status || "pending");
  if (root === "orders" && parts[2] === "contract") return contract(db, parts[1]);
  if (root === "orders" && parts[2] === "handoff") return handoff(db, parts[1], body.status || "sent");
  if (root === "orders") return createOrder(db, body.proposal_id);
  if (root === "contracts" && parts[2] === "transition") { if (!["generated","sent_simulated","signed","refused","cancelled"].includes(body.status)) return out({ error: "Estado de contrato inválido" }, 400); const { data: c } = await db.from("ds_contracts").update({ status: body.status, updated_at: now() }).eq("id", parts[1]).select().single(); if (c) { const { data: o } = await db.from("ds_orders").select("lead_slug").eq("id", c.order_id).single(); await event(db, o?.lead_slug, `contract.${body.status}`, c.id); } return out(c); }
  if (root === "qualifications") { const row = { id: id("qual"), lead_slug: body.lead_slug, facts: body.facts || [], hypotheses: body.hypotheses || [], recommendation: body.recommendation || "insufficient", reason: body.reason || "", confidence: body.confidence || "low", validation_question: body.validation_question || "", next_action: body.next_action || "", owner: body.owner || "" }; const { error } = await db.from("ds_qualifications").insert(row); if (error) return storageUnavailable(); await db.from("ds_leads").update({ product_suggested: row.recommendation === "insufficient" ? "" : row.recommendation, product_reason: row.reason, next_action: row.next_action }).eq("slug", row.lead_slug); await event(db, row.lead_slug, "qualification.created", row.id); return out(row); }
  if (root === "diagnoses") { const row = { id: id("diag"), lead_slug: body.lead_slug, criteria: body.criteria || [] }; const { error } = await db.from("ds_site_diagnoses").insert(row); if (error) return storageUnavailable(); await event(db, row.lead_slug, "site_diagnosis.created", row.id); return out(row); }
  if (root === "social-audits") { const disallowed = firstDisallowedKey(body, SOCIAL_AUDIT_INPUT_KEYS); if (disallowed) return out({ error: "social_audit_field_not_allowed" }, 400); const row = { id: id("social"), ...body }; const { error } = await db.from("ds_social_audits").insert(row); if (error) return storageUnavailable(); await event(db, row.lead_slug, "social_audit.created", row.id); return out(row); }
  if (root === "previews") { const { data: lead } = await db.from("ds_leads").select("nome,email,whatsapp,site_antigo").eq("slug", body.lead_slug).maybeSingle(); if (!lead) return out({ error: "Lead não encontrado" }, 404); const contact = lead.email || lead.whatsapp || lead.site_antigo || "Contato público não informado"; const pid = id("preview"), content = `<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${escapeHtml(lead.nome || body.lead_slug)}</title><body style="font-family:system-ui;max-width:760px;margin:40px auto;padding:24px"><small>PREVIEW / DEMO — revisão humana obrigatória</small><h1>${escapeHtml(lead.nome || body.lead_slug)}</h1><p>Prévia baseada somente nos dados registrados no CRM.</p><p><b>Contato:</b> ${escapeHtml(contact)}</p></body>`; const row = { id: pid, lead_slug: body.lead_slug, kind: body.kind || "redesign", url: `/api/previews/${pid}`, content, status: "published_mock" }; await db.from("ds_previews").insert(row); await event(db, row.lead_slug, "preview.published_mock", row.id); return out(row); }
  return out({ error: "route_not_found" }, 404);
}

export async function PUT(request: Request, { params }: { params: Promise<{ path: string[] }> }) {
  const auth = await context(); if (!auth) return out({ error: "unauthorized" }, 401); const { db } = auth; const parts = (await params).path; const body = await request.json().catch(() => ({}));
  if (parts[0] === "leads" && parts[1]) { if (!isSafeLeadSlug(parts[1])) return out({ error: "invalid_lead_slug" }, 400); const disallowed = firstDisallowedKey(body, LEAD_INPUT_KEYS); if (disallowed) return out({ error: "lead_field_not_allowed" }, 400); const row = uiToLead(body); delete row.slug; if (row.status === "fechado") { const value = Number(row.valor_fechado ?? row.valor); if (body.closingConfirmed !== true || value <= 0) return out({ error: "Fechamento exige confirmação explícita e valor_fechado positivo." }, 400); row.valor = value; row.valor_fechado = value; row.closing_confirmed_at = now(); } row.updated_at = now(); const { error } = await db.from("ds_leads").update(row).eq("slug", parts[1]).is("deleted_at", null); return error ? storageUnavailable() : out({ ok: true }); }
  if (parts[0] === "settings") { const allowed = new Set(["company_name","seller_name","signature","phone","whatsapp","region","identity","language","demo_mode","limits","email_provider","email_sender","email_reply_to","spf_status","dkim_status","dmarc_status","hour_limit","day_limit","followup_days"]); const rows = Object.entries(body).filter(([key]) => allowed.has(key) && !/(secret|key|password)/i.test(key)).map(([key, value]) => ({ key, value, updated_at: now() })); if (rows.length) await db.from("ds_settings").upsert(rows); return out(await settings(db)); }
  if (parts[0] === "products" && parts[1]) { const allowed = ["name","billing","public_price","base_price","cost","commission_pct","max_discount_pct","currency","active","terms","description","checkout_url","cta_label","availability"]; const row = Object.fromEntries(Object.entries(body).filter(([key]) => allowed.includes(key))); row.updated_at = now(); const { data, error } = await db.from("ds_products").update(row).eq("id", parts[1]).select().single(); return error ? storageUnavailable() : out(data); }
  if (parts[0] === "emails" && parts[1]) { if (!String(body.subject || "").trim() || !String(body.body || "").trim()) return out({ error: "Assunto e corpo são obrigatórios" }, 400); const { data: current } = await db.from("ds_emails").select("*").eq("id", parts[1]).single(); if (!current || !["draft","reviewed"].includes(current.status)) return out({ error: "Somente rascunhos ou e-mails em revisão podem ser editados" }, 400); const { data } = await db.from("ds_emails").update({ subject: body.subject.trim(), body: body.body.trim(), updated_at: now() }).eq("id", parts[1]).select().single(); await event(db, current.lead_slug, "email.edited", current.id); return out(data); }
  if (parts[0] === "proposals" && parts[1]) { const { data: p } = await db.from("ds_proposals").select("*,ds_products(cost,max_discount_pct)").eq("id", parts[1]).single(); if (!p) return out({ error: "Proposta não encontrada" }, 404); const price = Number(body.negotiated_price ?? p.negotiated_price), discount = Number(p.base_price) - price, product = p.ds_products as unknown as { cost: number; max_discount_pct: number }; if (price <= 0 || discount > Number(p.base_price) * Number(product.max_discount_pct) / 100) return out({ error: "Preço inválido ou desconto acima do máximo" }, 400); await db.from("ds_proposals").update({ status: "revised" }).eq("id", p.id); const row = { ...p, ds_products: undefined, id: id("prop"), negotiated_price: price, discount, margin: price - Number(product.cost), terms: body.terms ?? p.terms, valid_until: new Date(Date.now() + Number(body.valid_days || 7) * 86400000).toISOString(), version: Number(p.version) + 1, status: "draft", created_at: now() }; await db.from("ds_proposals").insert(row); await event(db, p.lead_slug, "proposal.revised", row.id); return out(row); }
  if (parts[0] === "previews" && parts[1]) { const content = `<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width"><body style="font-family:system-ui;max-width:760px;margin:40px auto;padding:24px"><small>PREVIEW / DEMO — revisão humana obrigatória</small><h1>${escapeHtml(body.title)}</h1><p>${escapeHtml(body.body)}</p><p><b>CTA:</b> ${escapeHtml(body.cta)}</p><p><b>Contato:</b> ${escapeHtml(body.contact)}</p></body>`; const { data } = await db.from("ds_previews").update({ content }).eq("id", parts[1]).select().single(); return out(data); }
  return out({ error: "route_not_found" }, 404);
}

export async function DELETE(_request: Request, { params }: { params: Promise<{ path: string[] }> }) { const auth = await context(); if (!auth) return out({ error: "unauthorized" }, 401); const parts = (await params).path; if (parts[0] === "leads" && parts[1]) { if (!isSafeLeadSlug(parts[1])) return out({ error: "invalid_lead_slug" }, 400); const { data: paidOrder, error: paidOrderError } = await auth.db.from("ds_orders").select("id").eq("lead_slug", parts[1]).eq("status", "paid").limit(1).maybeSingle(); if (paidOrderError) return storageUnavailable(); if (paidOrder) return out({ error: "lead_delete_forbidden_paid_order" }, 409); const { error } = await auth.db.from("ds_leads").update({ deleted_at: now(), updated_at: now() }).eq("slug", parts[1]).is("deleted_at", null); return error ? storageUnavailable() : out({ ok: true }); } return out({ error: "route_not_found" }, 404); }

async function transitionEmail(db: Db, emailId: string, status: string, fixture = "") { const allowed = ["reviewed","approved","sent_simulated","delivered_simulated","positive_reply","negative_reply","bounce","failed","no_reply","generic_reply"]; if (!allowed.includes(status)) return out({ error: "Estado de e-mail inválido" }, 400); const { data: email } = await db.from("ds_emails").select("*").eq("id", emailId).single(); if (!email) return out({ error: "E-mail não encontrado" }, 404); if (status === "sent_simulated" && email.status !== "approved") return out({ error: "Somente rascunho aprovado pode ser enviado" }, 400); let provider = email.provider, provider_message_id = email.provider_message_id, finalStatus = status, error: string | null = null; if (status === "sent_simulated") { const cfg = await settings(db); const configurationError = resendConfigurationError(cfg.email_provider, Boolean(process.env.RESEND_API_KEY)); if (configurationError) { error = configurationError; finalStatus = "failed"; } else if (cfg.email_provider === "resend") { try { const result = await new Resend(process.env.RESEND_API_KEY!).emails.send({ from: String(cfg.email_sender), to: [email.recipient], replyTo: cfg.email_reply_to ? String(cfg.email_reply_to) : undefined, subject: email.subject, text: email.body, headers: { "X-Entity-Ref-ID": email.id } }); if (result.error) throw new Error(result.error.message); provider = "resend"; provider_message_id = result.data?.id; finalStatus = "sent"; } catch { error = "provider_send_failed"; finalStatus = "failed"; } } } const { data } = await db.from("ds_emails").update({ status: finalStatus, provider, provider_message_id, error, attempt: Number(email.attempt) + (status === "sent_simulated" ? 1 : 0), updated_at: now() }).eq("id", emailId).select().single(); await event(db, email.lead_slug, `email.${finalStatus}`, fixture || emailId); return out(data ?? { ok: true, status: finalStatus }); }
async function createOrder(db: Db, proposalId: string) { const { data: p } = await db.from("ds_proposals").select("*,ds_products(*)").eq("id", proposalId).single(); if (!p) return out({ error: "Proposta não encontrada" }, 404); const cfg = await settings(db), seller = String(cfg.seller_name ?? "").trim(), product = p.ds_products as unknown as Record<string, unknown>; if (!seller) return out({ error: "seller_name_required" }, 409); const row = { id: id("ord"), lead_slug: p.lead_slug, product_id: p.product_id, offer_name: product.name, seller, base_price: p.base_price, negotiated_price: p.negotiated_price, discount: p.discount, cost: product.cost, margin: p.margin, currency: p.currency, commission_pct: product.commission_pct, status: "open" }; const { error } = await db.from("ds_orders").insert(row); if (error) return storageUnavailable(); await db.from("ds_proposals").update({ status: "accepted" }).eq("id", proposalId); await event(db, row.lead_slug, "order.created", row.id); return out(row); }
async function checkout(db: Db, orderId: string, result?: string) { const { data: order } = await db.from("ds_orders").select("lead_slug").eq("id", orderId).single(); if (!order) return out({ error: "Pedido não encontrado" }, 404); let { data: ck } = await db.from("ds_checkouts").select("*").eq("order_id", orderId).maybeSingle(); if (!ck) { ck = { id: id("checkout"), order_id: orderId, status: "open", expires_at: new Date(Date.now() + 86400000).toISOString() }; await db.from("ds_checkouts").insert(ck); await event(db, order.lead_slug, "checkout.open", ck.id); } if (result && ["completed","abandoned","expired"].includes(result)) { ck.status = result; await db.from("ds_checkouts").update({ status: result }).eq("order_id", orderId); await event(db, order.lead_slug, `checkout.${result}`, ck.id); } return out(ck); }
async function payment(db: Db, orderId: string, status: string) { if (!["pending","approved","declined","cancelled","refunded"].includes(status)) return out({ error: "Pagamento inválido" }, 400); const { data: order } = await db.from("ds_orders").select("*").eq("id", orderId).single(); if (!order) return out({ error: "Pedido não encontrado" }, 404); let { data: pay } = await db.from("ds_payments").select("*").eq("order_id", orderId).maybeSingle(); if (pay?.status === "approved") return out(pay); if (pay) { const response = await db.from("ds_payments").update({ status, updated_at: now() }).eq("order_id", orderId).select().single(); pay = response.data; } else { pay = { id: id("pay"), order_id: orderId, status, amount: order.negotiated_price, currency: order.currency }; await db.from("ds_payments").insert(pay); } await db.from("ds_orders").update({ status: status === "approved" ? "paid" : status }).eq("id", orderId); await event(db, order.lead_slug, `payment.${status}`, orderId); if (status === "approved") { await db.from("ds_handoffs").upsert({ id: id("hand"), order_id: orderId, product_id: order.product_id, client: order.lead_slug, seller: order.seller, requirements: "", status: "pending", retry_count: 0 }, { onConflict: "order_id", ignoreDuplicates: true }); await db.from("ds_commissions").upsert({ id: id("comm"), order_id: orderId, seller: order.seller, base: order.negotiated_price, pct: order.commission_pct, amount: Number(order.negotiated_price) * Number(order.commission_pct) / 100, state: "pending" }, { onConflict: "order_id", ignoreDuplicates: true }); await event(db, order.lead_slug, "handoff.created", orderId); } return out(pay); }
async function contract(db: Db, orderId: string) { const { data: o } = await db.from("ds_orders").select("*,ds_leads(nome,empresa,cidade),ds_products(is_demo,terms)").eq("id", orderId).single(); if (!o) return out({ error: "Pedido não encontrado" }, 404); const product = o.ds_products as unknown as { is_demo?: boolean; terms?: string }; if (product?.is_demo === true) return out({ error: "demo_product_contract_forbidden" }, 409); const lead = o.ds_leads as unknown as Record<string, string>, html = `<!doctype html><meta charset="utf-8"><title>Contrato DattaSeller</title><body style="font-family:serif;max-width:800px;margin:40px auto;line-height:1.55"><h1>Contrato de prestação de serviços</h1><p><b>Cliente:</b> ${escapeHtml(lead?.nome || o.lead_slug)}</p><p><b>Oferta:</b> ${escapeHtml(o.offer_name)}</p><p><b>Valor:</b> ${escapeHtml(o.currency)} ${Number(o.negotiated_price).toFixed(2)}</p><p><b>Condições:</b> ${escapeHtml(product?.terms || "a confirmar")}</p><p>Documento gerado pelo fluxo DattaSeller. Revisão humana obrigatória antes da assinatura.</p></body>`; const existing = await db.from("ds_contracts").select("id").eq("order_id", orderId).maybeSingle(); const row = { id: existing.data?.id || id("contract"), order_id: orderId, status: "generated", html, updated_at: now() }; await db.from("ds_contracts").upsert(row, { onConflict: "order_id" }); await event(db, o.lead_slug, "contract.generated", orderId); return out(row); }
async function handoff(db: Db, orderId: string, status: string) { if (!["pending","sent","executing","delivered","failed"].includes(status)) return out({ error: "Handoff inválido" }, 400); const { data: h } = await db.from("ds_handoffs").select("*").eq("order_id", orderId).single(); if (!h) return out({ error: "Handoff só existe após pagamento aprovado" }, 400); const retry = status === "sent" && h.status === "failed", patch = { status, retry_count: Number(h.retry_count) + (retry ? 1 : 0), error: retry ? null : h.error, updated_at: now() }; const { data } = await db.from("ds_handoffs").update(patch).eq("order_id", orderId).select().single(); const { data: o } = await db.from("ds_orders").select("lead_slug").eq("id", orderId).single(); await event(db, o?.lead_slug, retry ? "handoff.retry" : `handoff.${status}`, orderId); return out(data); }
const escapeHtml = (value: unknown) => String(value ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
